name: Linting and Pre-commit checks for the jvspatial

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit-jvspatial:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install package with dev dependencies
      run: pip install -e '.[dev]'

    - name: Run pre-commit hooks
      run: pre-commit run --files $(find . -type f)