name: Test jvspatial

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd jvspatial
        pip install pytest pytest-asyncio
        pip install pydantic fastapi
        pip install -e .

    - name: Run tests
      run: |
        cd jvspatial
        pytest tests/ -v --tb=short

    - name: Run pre-commit checks
      run: |
        cd jvspatial
        pip install pre-commit
        pre-commit run --all-files